services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-web3
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=secret'
    ports:
      - '8081:80'
    networks:
      - backend-network

networks:
  backend-network: