spring:
  application:
    name: crypto-wallet
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.schema}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
db:
  host: localhost
  port: 5432
  schema: mydatabase
  username: myuser
  password: secret

logging:
  file:
    name: ./log/spring.log

app:
  secret-key: "your-secret-key"
  jwt-secret-key: "your-jwt-secret"